### ISSUE TITLE
Switch API format to JSON API

### ISSUE THREAD

**Issue by thegcat** [thegcat/oskiosk#22]
This will allow for some good things like passing errors and the current state of the resource at the same time. This will break the clients in one fell swoop though, and is in RC3, i.e. might be a little wobbly around the edges.

@fabian-rump as you are currently the only consumer of the API, would you be able to cater for this? I _think_ the biggest and probably only relevant change for you would be that the objects of interest reside under the key `data`. If you're ok with this, I'd also like to do a few other changes (for example rename `cart.user_id` to `cart.customer`)

**Comment by fabian-rump** [comment]
No problem for me. I am currently porting the code to Angular JS to get a more flexible and reusable code base (i.e. for future extensions such as a full service client, menu/dialogs, ...). Hence I need to do some changes to the code either way, so I am perfectly fine with integrating new stuff.

**Comment by thegcat** [comment]
Oi, I like that the client goes the way of the javascript, I'd probably have tried Ember.js though :-)

**Comment by thegcat** [comment]
I will try to draft the changes in the next few days and we can decide wether to go on with it before the weekend or not.

**Comment by thegcat** [comment]
Hehe, due to the recent changes to JSON API bringing it to RC3, the library I use is not ready yet :sweat_smile: so this will probably not be ready for this weekend.

I started the work in apotonick/roar#143, but we can discuss this weekend if we want to push it if it's ready for the end of may, or if we should stick to what we have.
