### ISSUE TITLE
What should transactions look like

### ISSUE THREAD

**Issue by thegcat** [thegcat/oskiosk#28]
@fabian-rump this one is for you especially

I'm having a little trouble figuring out what the fields for a transaction should be. We will have until Aachen at least 2 types: cart payments and user deposits.

Should those be kept as generic as possible, i.e. in both cases there is an amount, a user (either paying the cart or making the deposit), and so on, and it's up to the client to figure out which is which case, or should those be returned with custom field names, i.e. customer for cart payments and payee for deposits?

**Comment by fabian-rump** [comment]
Both options would be totally ok. The question at hand is: Do you plan to reference the paid cart with its items in some way? Or more general: How do you keep track about which items a user bought? I think the most elegant way would be to keep the cart with its items in the system and lock it when creating the transaction. Then for each transaction it would be sufficient to reference either a cart entity or a deposit entity.

**Comment by thegcat** [comment]
Transactions relating to cart payments look something like that in the backend:

``` json
{
  "buyer_name": "Joe Smith",
  "user_id": "123",
  "total_price": "1000",
  "transaction_items": [
    "product_id": "123",
    "price": "200",
    "quantity": "5"
  ]
}
```

The structure is similar to the cart, but denormalises some stuff so that the name of the buyer and the price and name of the product at the moment of the purchase are stored with the transaction.

I'll probably go with the generic version though, with a `transaction_type` so that the client can decide what to do with it.

I'll have to decide whether to have a "product" called deposit so that deposit transactions don't have empty transaction_items or not. Tying them to a special product has the benefit of being able to query those as would be possible with "other products".

**Comment by thegcat** [comment]
See http://thegcat.github.io/oskiosk/#!/transactions/Transactions_create for an example of what a Transaction response looks like.
