### ISSUE TITLE
Query interface for Transactions

### ISSUE THREAD

**Issue by thegcat** [thegcat/oskiosk#30]
Because statistics! /cc @fabian-rump

**Comment by thegcat** [comment]
We should probably use https://rubygems.org/gems/ransack for this.

**Comment by thegcat** [comment]
Ransack looks good, Will probably land in the next few days.

**Comment by fabian-rump** [comment]
Before you move forward with the implementation, let me provide some input from the client side. Specifically, Angular JS supports filtering and aggregation directly in the client, given that the API can provide a rather "raw" data output at a suitable granularity. I have some ideas how to build a nice admin statistics interface in mind, but need to read through some pieces of the documentation to formulate the exact requirements which I would need to implement this. Maybe I can do this tomorrow on my way back from Berlin to Bonn. Just poke me if I forget to get back on this ;-)

**Comment by thegcat** [comment]
Bäm, there is now the possibility to search and filter for transactions. See the email I sent you for some examples. Once you have something working off of that for stats, we can also have a quick chat to see how to define the queries you'd need.

**Comment by thegcat** [comment]
Oh, and there's no docs for that now, ping me if I forget.

**Comment by thegcat** [comment]
Last but not least: as this allows some fine-grained stuff, I'd keep it behind a specific app token only for this purpose that we should keep a good eye on.
