### ISSUE TITLE
Requesting non-existing identifiers returns error 500

### ISSUE THREAD

**Issue by fabian-rump** [thegcat/oskiosk#4]
Requesting a non-existing identifier results in a HTTP 500 error. This should not be the case. Instead the system should return error 404 so that a client can distinguish a non-existing code from a real server-side error.

Example:

Request URL
https://oskiosk.herokuapp.com:443/identifiers/1234.json

Response Body
{
  "status": "500",
  "error": "Internal Server Error"
}

Response Code
500

Response Headers
{
  "content-type": "application/json; charset=utf-8"
}

**Comment by thegcat** [comment]
Fixed in ffe4296.
