### ISSUE TITLE
Sending malformed JSON when creating a cart returns error 500

### ISSUE THREAD

**Issue by fabian-rump** [thegcat/oskiosk#6]
When sending a malformed JSON payload (or no JSON at all) to create a cart, error 500 is returned:

{
  "status": "500",
  "error": "Internal Server Error"
}

Instead error 400 should be returned:

{
  "status": "400",
  "error": "Bad Request"
}

**Comment by thegcat** [comment]
I tried this with `curl -v -H "content-type: application/json" -H "Authorization: …"  --data '' -X POST https://oskiosk.herokuapp.com/carts` with different values for `data`:

1. `''` (empty string) will happily create a cart,
2. `'12345'` (not JSON) makes the app crap itself with a 500,
3. `'abcd'` (also not JSON) will get a 400,
4. `'{"foo":1'` (malformed JSON) will get a 400.

From my understanding only 2 is a problem as it should return a 400 instead, correct?

**Comment by thegcat** [comment]
It seems Rails tries to be too smart for its own good.
